In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('training.csv')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
Unnamed: 0                              150000 non-null int64
SeriousDlqin2yrs                        150000 non-null int64
RevolvingUtilizationOfUnsecuredLines    150000 non-null float64
age                                     150000 non-null int64
NumberOfTime30-59DaysPastDueNotWorse    150000 non-null int64
DebtRatio                               150000 non-null float64
MonthlyIncome                           120269 non-null float64
NumberOfOpenCreditLinesAndLoans         150000 non-null int64
NumberOfTimes90DaysLate                 150000 non-null int64
NumberRealEstateLoansOrLines            150000 non-null int64
NumberOfTime60-89DaysPastDueNotWorse    150000 non-null int64
NumberOfDependents                      146076 non-null float64
dtypes: float64(4), int64(8)
memory usage: 13.7 MB

In [3]:
df.describe()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.202690e+05,150000.000000,150000.000000,150000.000000,150000.000000,146076.000000
mean,75000.500000,0.066840,6.048438,52.295207,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387,0.757222
std,43301.414527,0.249746,249.755371,14.771866,4.192781,2037.818523,1.438467e+04,5.145951,4.169304,1.129771,4.155179,1.115086
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,37500.750000,0.000000,0.029867,41.000000,0.000000,0.175074,3.400000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,75000.500000,0.000000,0.154181,52.000000,0.000000,0.366508,5.400000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,112500.250000,0.000000,0.559046,63.000000,0.000000,0.868254,8.249000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,150000.000000,1.000000,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000

In [4]:
df.head()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [5]:
df.shape

(150000, 12)

In [6]:
df.columns

Index(['Unnamed: 0', 'SeriousDlqin2yrs',
       'RevolvingUtilizationOfUnsecuredLines', 'age',
       'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome',
       'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate',
       'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse',
       'NumberOfDependents'],
      dtype='object')

In [8]:
df.isnull()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,True,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,True,False,False,False,False,True
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,True,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
149970,False,False,False,False,False,False,False,False,False,False,False,False
149971,False,False,False,False,False,False,False,False,False,False,False,False
149972,False,False,False,False,False,False,False,False,False,False,False,False
149973,False,False,False,False,False,False,False,False,False,False,False,False
149974,False,False,False,False,False,False,False,False,False,False,False,False
149975,False,False,False,False,False,False,True,False,False,False,False,False
149976,False,False,False,False,False,False,True,False,False,False,False,False
149977,False,False,False,False,False,False,True,False,False,False,False,False
149978,False,False,False,False,False,False,False,False,False,False,False,False
149979,False,False,False,False,False,False,False,False,False,False,False,False
149980,False,False,False,False,False,False,False,False,False,False,False,False
149981,False,False,False,False,False,False,False,False,False,False,False,False
149982,False,False,False,False,False,False,False,False,False,False,False,False
149983,False,False,False,False,False,False,False,False,False,False,False,False
149984,False,False,False,False,False,False,True,False,False,False,False,False
149985,False,False,False,False,False,False,False,False,False,False,False,False
149986,False,False,False,False,False,False,False,False,False,False,False,False
149987,False,False,False,False,False,False,False,False,False,False,False,False
149988,False,False,False,False,False,False,False,False,False,False,False,False
149989,False,False,False,False,False,False,False,False,False,False,False,False
149990,False,False,False,False,False,False,False,False,False,False,False,False
149991,False,False,False,False,False,False,False,False,False,False,False,False
149992,False,False,False,False,False,False,True,False,False,False,False,False
149993,False,False,False,False,False,False,False,False,False,False,False,False
149994,False,False,False,False,False,False,False,False,False,False,False,False
149995,False,False,False,False,False,False,False,False,False,False,False,False
149996,False,False,False,False,False,False,False,False,False,False,False,False
149997,False,False,False,False,False,False,True,False,False,False,False,False
149998,False,False,False,False,False,False,False,False,False,False,False,False
149999,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
df

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
5,6,0,0.213179,74,0,0.375607,3500.0,3,0,1,0,1.0
6,7,0,0.305682,57,0,5710.000000,NaN,8,0,3,0,0.0
7,8,0,0.754464,39,0,0.209940,3500.0,8,0,0,0,0.0
8,9,0,0.116951,27,0,46.000000,NaN,2,0,0,0,NaN
9,10,0,0.189169,57,0,0.606291,23684.0,9,0,4,0,2.0
10,11,0,0.644226,30,0,0.309476,2500.0,5,0,0,0,0.0
11,12,0,0.018798,51,0,0.531529,6501.0,7,0,2,0,2.0
12,13,0,0.010352,46,0,0.298354,12454.0,13,0,2,0,2.0
13,14,1,0.964673,40,3,0.382965,13700.0,9,3,1,1,2.0
14,15,0,0.019657,76,0,477.000000,0.0,6,0,1,0,0.0
15,16,0,0.548458,64,0,0.209892,11362.0,7,0,1,0,2.0
16,17,0,0.061086,78,0,2058.000000,NaN,10,0,2,0,0.0
17,18,0,0.166284,53,0,0.188274,8800.0,7,0,0,0,0.0
18,19,0,0.221813,43,0,0.527888,3280.0,7,0,1,0,2.0
19,20,0,0.602794,25,0,0.065868,333.0,2,0,0,0,0.0
20,21,0,0.200923,43,0,0.430046,12300.0,10,0,2,0,0.0
21,22,1,0.025656,38,0,0.475841,3000.0,7,0,1,0,2.0
22,23,0,1.000000,39,0,0.241104,2500.0,4,0,0,0,0.0
23,24,0,0.075427,32,0,0.085512,7916.0,6,0,0,0,0.0
24,25,0,0.046560,58,0,0.241622,2416.0,9,0,1,0,0.0
25,26,1,0.392248,50,0,1.595253,4676.0,14,0,3,0,1.0
26,27,0,0.052436,58,0,0.097672,8333.0,22,0,1,0,0.0
27,28,0,0.034421,69,0,0.042383,2500.0,17,0,0,0,1.0
28,29,0,0.452516,24,0,0.011761,3400.0,1,0,0,0,0.0
29,30,0,0.392995,58,2,0.436103,5500.0,15,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
149970,149971,0,0.025449,58,0,0.253855,15500.0,7,0,2,0,2.0
149971,149972,0,0.058001,83,0,0.013997,5000.0,6,0,0,0,0.0
149972,149973,0,0.071273,42,0,0.008638,6945.0,3,0,0,0,1.0
149973,149974,0,1.026395,44,0,0.494819,5500.0,7,0,1,0,1.0
149974,149975,0,0.962721,61,2,0.603479,5000.0,11,0,1,0,0.0
149975,149976,0,0.022088,58,0,2716.000000,NaN,8,0,2,0,0.0
149976,149977,0,0.000627,76,0,60.000000,NaN,5,0,0,0,0.0
149977,149978,0,0.236450,29,0,349.000000,NaN,3,0,0,0,0.0
149978,149979,0,0.917635,52,2,0.259496,2500.0,4,0,0,0,0.0
149979,149980,1,0.224711,55,0,0.057235,8700.0,7,0,0,0,0.0
149980,149981,0,0.067644,64,0,0.254976,5525.0,12,0,1,0,0.0
149981,149982,0,0.810012,43,0,0.121752,6849.0,4,0,0,0,4.0
149982,149983,0,0.021046,37,0,0.250272,2760.0,8,0,0,0,3.0
149983,149984,0,0.002485,82,0,0.000800,5000.0,5,0,0,0,0.0
149984,149985,0,0.037548,84,0,25.000000,NaN,5,0,0,0,0.0
149985,149986,0,0.954409,26,0,0.324962,1950.0,4,0,0,0,0.0
149986,149987,0,0.168102,49,0,0.080384,5000.0,16,0,0,0,1.0
149987,149988,0,1.000000,28,0,0.055692,3249.0,3,1,0,0,0.0
149988,149989,0,0.902051,31,1,0.347924,7515.0,10,0,1,0,0.0
149989,149990,0,0.013356,62,0,0.001408,9233.0,4,0,0,0,3.0
149990,149991,0,0.055518,46,0,0.609779,4335.0,7,0,1,0,2.0
149991,149992,0,0.104112,59,0,0.477658,10316.0,10,0,2,0,0.0
149992,149993,0,0.871976,50,0,4132.000000,NaN,11,0,1,0,3.0
149993,149994,0,1.000000,22,0,0.000000,820.0,1,0,0,0,0.0
149994,149995,0,0.385742,50,0,0.404293,3400.0,7,0,0,0,0.0
149995,149996,0,0.040674,74,0,0.225131,2100.0,4,0,1,0,0.0
149996,149997,0,0.299745,44,0,0.716562,5584.0,4,0,1,0,2.0
149997,149998,0,0.246044,58,0,3870.000000,NaN,18,0,1,0,0.0
149998,149999,0,0.000000,30,0,0.000000,5716.0,4,0,0,0,0.0
149999,150000,0,0.850283,64,0,0.249908,8158.0,8,0,2,0,0.0

In [4]:
df.fillna(df.mean,inplace=True)

In [11]:
df.isnull().sum()

Unnamed: 0                              0
SeriousDlqin2yrs                        0
RevolvingUtilizationOfUnsecuredLines    0
age                                     0
NumberOfTime30-59DaysPastDueNotWorse    0
DebtRatio                               0
MonthlyIncome                           0
NumberOfOpenCreditLinesAndLoans         0
NumberOfTimes90DaysLate                 0
NumberRealEstateLoansOrLines            0
NumberOfTime60-89DaysPastDueNotWorse    0
NumberOfDependents                      0
dtype: int64

In [ ]:
df['MonthlyIncome'].describe()